routes/web.php
    Route::post('/store_max_file_size', ['uses'=>'SettingController@store_max_file_size', 'as'=>'store_max_file_size'])->middleware('can:setting-change');
    Route::post('/logo', ['uses'=>'SettingController@store_logo', 'as'=>'store_logo'])->middleware('can:setting-change');
    Route::post('/contact_info', ['uses'=>'SettingController@store_contact_info', 'as'=>'contact_info'])->middleware('can:setting-change');
});

Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => 'auth', 'as' => 'profile.'], function () {
    Route::get('/view/{id}', ['uses'=>'ProfileController@view','as'=>'view']);
    Route::post('/update/{type}', ['uses'=>'ProfileController@update','as'=>'update']);
});

Route::group(['prefix' =>ROOT_DIR.'slider', 'middleware' => 'auth', 'as' => 'slider.'], function () {
    Route::get('/list', ['uses'=>'SliderController@index','as'=>'index'])->middleware('can:slider-list');
    Route::post('/add', ['uses'=>'SliderController@create','as'=>'add'])->middleware('can:slider-add');
    Route::get('/edit/{slider_id}', ['uses'=>'SliderController@edit','as'=>'edit'])->middleware('can:slider-add');
    Route::post('/update', ['uses'=>'SliderController@update','as'=>'update'])->middleware('can:slider-add');
    Route::get('/activate/{id}/{action}', ['uses'=>'SliderController@set_active','as'=>'activate'])->middleware('can:slider-add');
    Route::post('/delete', ['uses'=>'SliderController@delete','as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'pages', 'middleware' => 'auth', 'as' => 'pages.'], function () {
    Route::get('/list', ['uses'=>'PostController@index','as'=>'index'])->middleware('can:pages-list');
    Route::get('/add', ['uses'=>'PostController@create','as'=>'add'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'PostController@store'])->middleware('can:pages-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@edit', 'as'=> 'edit'])->middleware('can:pages-edit');
    Route::post('/update', ['uses'=>'PostController@update', 'as'=> 'update'])->middleware('can:pages-edit');
    Route::post('/create_url', ['uses'=>'PostController@create_url', 'as'=>'create_url'])->middleware('can:pages-add');
    Route::post('/recycle', ['uses'=>'PostController@recycle', 'as'=>'recycle'])->middleware('can:pages-delete');
    Route::post('/make_featured', ['uses'=>'PostController@make_featured', 'as'=>'make_featured']);
});

Route::group(['prefix' =>ROOT_DIR.'menu', 'middleware' => 'auth', 'as' => 'menu.'], function () {
    Route::get('/list', ['uses'=>'MenuController@index','as'=>'index'])->middleware('can:menu-list');
    Route::post('/add', ['uses'=>'MenuController@create','as'=>'add'])->middleware('can:menu-add');
    Route::post('/change', ['uses'=>'MenuController@change','as'=>'change'])->middleware('can:menu-add');
    Route::get('/remove_item/{menu_post_id}', ['uses'=>'MenuController@remove_item','as'=>'remove_item'])->middleware('can:menu-add');
    Route::post('/edit_menu', ['uses'=>'MenuController@edit_menu','as'=>'edit_menu'])->middleware('can:menu-add');
    Route::post('/saveOrder', ['uses'=>'MenuController@saveOrder','as'=>'saveOrder'])->middleware('can:menu-add');
    Route::get('/change_status/{menu_id}/{action}', ['uses'=>'MenuController@change_status','as'=>'change_status'])->middleware('can:menu-add');
});

Route::group(['prefix' =>ROOT_DIR.'gallery', 'middleware' => 'auth', 'as' => 'gallery.'], function () {
    Route::get('/list', ['uses'=>'GalleryController@index','as'=>'index'])->middleware('can:gallery-list');
    Route::post('/add', ['uses'=>'GalleryController@create','as'=>'add'])->middleware('can:gallery-add');
    Route::get('/view/{id}', ['uses'=>'GalleryController@display','as'=>'view'])->middleware('can:gallery-list');
    Route::post('/edit', ['uses'=>'GalleryController@edit','as'=>'edit'])->middleware('can:gallery-edit');
    Route::post('/delete_gallery', ['uses'=>'GalleryController@delete_gallery','as'=>'delete_gallery'])->middleware('can:gallery-delete');
    Route::group(['prefix' =>'image', 'middleware' => 'auth', 'as' => 'image.'], function () {
        Route::post('/add', ['uses'=>'GalleryController@add_image','as'=>'add'])->middleware('can:gallery-edit');
        Route::post('/delete', ['uses'=>'GalleryController@delete_image','as'=>'delete'])->middleware('can:gallery-delete');
    });
});

Route::group(['prefix' =>ROOT_DIR.'category', 'middleware' => 'auth', 'as' => 'category.'], function () {
    Route::get('/list', ['uses'=>'CategoryController@index','as'=>'index'])->middleware('can:category-list');
    Route::get('/list_item/{id}', ['uses'=>'CategoryController@list_item','as'=>'list_item'])->middleware('can:category-list');
    Route::post('/store', ['uses'=>'CategoryController@store', 'as'=>'store'])->middleware('can:category-add');
    Route::post('/delete', ['uses'=>'CategoryController@delete_category','as'=>'delete'])->middleware('can:category-list');
    Route::post('/update', ['uses'=>'CategoryController@update_category','as'=>'update'])->middleware('can:category-list');

    // Items
    Route::get('/add_item/{category_id}', ['uses'=>'CategoryController@add_item', 'as'=>'add_item'])->middleware('can:category-add');
    Route::post('/store_item', ['uses'=>'CategoryController@store_item', 'as'=>'store_item'])->middleware('can:category-add');
    Route::post('/update_item', ['uses'=>'CategoryController@update_item', 'as'=>'update_item'])->middleware('can:category-add');
    Route::get('/edit_item/{item_id}', ['uses'=>'CategoryController@edit_item', 'as'=>'edit_item'])->middleware('can:category-add');
    Route::post('/delete_item', ['uses'=>'CategoryController@delete_item', 'as'=>'delete_item'])->middleware('can:category-add');
});

Route::group(['prefix' =>ROOT_DIR.'downloads', 'middleware' => 'auth', 'as' => 'downloads.'], function () {
    Route::get('/list', ['uses'=>'DownloadController@index', 'as'=>'index'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'DownloadController@store', 'as'=>'add'])->middleware('can:pages-add');
    Route::post('/edit', ['uses'=>'DownloadController@edit', 'as'=>'edit'])->middleware('can:pages-add');
    Route::post('/delete', ['uses'=>'DownloadController@delete', 'as'=>'delete'])->middleware('can:pages-add');
    Route::get('/download/{id}', ['uses'=>'DownloadController@download', 'as'=>'download'])->middleware('can:pages-add');
    Route::group(['prefix' =>'item', 'middleware' => 'auth', 'as' => 'item.'], function () {
        Route::get('/view_item/{id}', ['uses'=>'DownloadController@view_item', 'as'=>'view_item'])->middleware('can:pages-add');
        Route::post('/add', ['uses'=>'DownloadController@store_item', 'as'=>'add'])->middleware('can:pages-add');
        Route::post('/delete', ['uses'=>'DownloadController@delete_item', 'as'=>'delete'])->middleware('can:pages-add');
    });
});

// post route
Route::group(['prefix' =>ROOT_DIR.'post', 'middleware' => 'auth', 'as' => 'post.'], function () {
    Route::get('/list', ['uses'=>'PostController@get_post_index','as'=>'index'])->middleware('can:post-list');
    Route::get('/add', ['uses'=>'PostController@get_post_create','as'=>'add'])->middleware('can:post-add');
    Route::post('/add', ['uses'=>'PostController@post_store'])->middleware('can:post-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@get_post_edit', 'as'=> 'edit'])->middleware('can:post-add');
    Route::post('/update', ['uses'=>'PostController@post_update', 'as'=> 'update'])->middleware('can:post-add');
    Route::post('/recycle', ['uses'=>'PostController@post_recycle', 'as'=>'recycle'])->middleware('can:post-add');
});

// weblink route
Route::group(['prefix' =>ROOT_DIR.'weblink', 'middleware' => 'auth', 'as' => 'weblink.'], function () {
    Route::get('/list', ['uses'=>'WeblinkController@index','as'=>'index'])->middleware('can:weblink-list');
    Route::post('/add', ['uses'=>'WeblinkController@store','as'=>'add'])->middleware('can:weblink-add');
    Route::post('/delete', ['uses'=>'WeblinkController@delete','as'=>'delete'])->middleware('can:weblink-delete');
    // items
    Route::get('/view/{weblink_id}', ['uses'=>'WeblinkController@display','as'=>'view'])->middleware('can:weblink-item-list');
    Route::post('/item/update', ['uses'=>'WeblinkController@updateItem','as'=>'item.update'])->middleware('can:weblink-item-edit');
    Route::post('/item/addPost', ['uses'=>'WeblinkController@addPost','as'=>'item.addPost'])->middleware('can:weblink-item-add');
    Route::get('/item/remove/{weblink_post_id}', ['uses'=>'WeblinkController@removeItem','as'=>'item.remove'])->middleware('can:weblink-item-delete');
});

// job portal
Route::group(['prefix' =>ROOT_DIR.'jobs', 'middleware' => 'auth', 'as' => 'jobs.'], function () {
    Route::get('/list', ['uses'=>'JobController@index','as'=>'index'])->middleware('can:jobs-list');
    Route::get('/add', ['uses'=>'JobController@create','as'=>'add'])->middleware('can:jobs-add');
    Route::post('/add', ['uses'=>'JobController@store'])->middleware('can:jobs-add');
    Route::get('/edit/{job_id}', ['uses'=>'JobController@edit','as'=>'edit'])->middleware('can:jobs-edit');
    Route::post('/update', ['uses'=>'JobController@update','as'=>'update'])->middleware('can:jobs-edit');
    Route::post('/delete', ['uses'=>'JobController@delete','as'=>'delete'])->middleware('can:jobs-delete');
    Route::get('/applications/{job_id}', ['uses'=>'JobController@view_application', 'as'=>'application'])->middleware('can:jobs-list-application');
    Route::get('/application/export/{job_id}/{type}', ['uses'=>'JobController@export_users_application','as'=>'application.export_users'])->middleware('can:jobs-user-list');

    Route::group(['prefix' =>'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
        Route::get('/list', ['uses'=>'JobController@get_users','as'=>'index'])->middleware('can:jobs-user-list');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'gallery';
    public $timestamps = false;
    protected $dates = [
        'created_at'
    ];

    public function user()
    {
        return $this->belongsTo('App\User','created_by');
    }

    public function image()
    {
        return $this->hasMany('App\GalleryImage','gallery_id')->take(3)->orderBy('created_at','desc');
    }

    public function images()
    {
        return $this->hasMany('App\GalleryImage','gallery_id')->orderBy('created_at','desc');
    }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use Illuminate\Http\Request;
use App\Gallery;
use Auth;
use App\GalleryImage;

class GalleryController extends Controller
{
    private $image_post_max_size;
    public function __construct()
    {
        $this->image_post_max_size = Helper::image_post_max_size();
    }

    public function index(Request $request)
    {
    	$data['gallery'] = self::getImage();
        return view('gallery.index', $data);
    }

    private function getImage()
    {
        return Gallery::where('is_trashed',0)
                            ->with('image')
                            ->with('images')
                            ->with('user')
                            ->orderBy('created_at', 'desc')
                            ->get()
                            ->each(function($image) {
                                    $image->load('image');
                                });
    }

    public function create(Request $request)
    {
    	$this->validate($request,[
    		'gallery_name' => 'required|max:255',
            'description' => 'max:500'
    	]);
    	$gallery = new Gallery();
    	$gallery->gallery_name = $request->gallery_name;
    	$gallery->description = $request->description;
    	$gallery->is_trashed = 0;
    	$gallery->created_by = Auth::user()->id;
    	$gallery->created_at = date('Y-m-d H:i:s');
    	$gallery->save();

    	$flashMessage = [
            'heading'=>'success',
            'type'=>'success',
            'message'=>'Gallery created successfully.'
        ];
        \Session::flash('flash_message', $flashMessage);
        return redirect()->route('gallery.index');
    }

    public function add_image(Request $request)
    {
//        dd($request->all());
//        dd($this->image_post_max_size);
        $this->validate($request,[
            'image' => 'required',
            'image.*' => 'mimes:jpeg,bmp,png|max:'.$this->image_post_max_size,
        ]);
        foreach($request->file('image') as $img) {
            $path = $img->store('gallery', 'public');
            $gallery_image = new GalleryImage();
            $gallery_image->image_name = $path;
            $gallery_image->gallery_id = $request->gallery_id;
            $gallery_image->is_trashed = 0;
            $gallery_image->created_by = Auth::user()->id;
            $gallery_image->created_at = date('Y-m-d H:i:s');
            $gallery_image->save();
        }

        $flashMessage = [
            'heading'=>'success',
            'type'=>'success',
            'message'=>'Image added successfully.'
        ];
        \Session::flash('flash_message', $flashMessage);
        return redirect()->back();
    }

    public function display($id)
    {
        $data['gallery'] = Gallery::where('id',$id)->with('user')->with('images')->first();
        return view('gallery.display',$data);
    }

    public function edit(Request $request)
    {
        // dd($request->all());
        $this->validate($request,[
            'gallery_name' => 'required|max:255'
        ]);
        $gallery = Gallery::find($request->gallery_id);
        $gallery->gallery_name = $request->gallery_name;
        $gallery->description = $request->description;
        $gallery->save();

        return redirect()->back();
    }

    public function delete_gallery(Request $request)
    {
        $gallery = Gallery::find($request->id);
        $galleryImage = GalleryImage::where('gallery_id',$gallery->id)->get();
        foreach ($galleryImage as $value){
            \Storage::delete('public/'.$value->image_name);
            $value->delete();
        }
        $gallery->delete();
        $flashMessage = [
            'heading'=>'success',
            'type'=>'success',
            'message'=>'Gallery and images deleted successfully.'
        ];
        \Session::flash('flash_message', $flashMessage);
        return 's';
    }

    public function delete_image(Request $request)
    {
        $image = GalleryImage::find($request->id);
        \Storage::delete('public/'.$image->image_name);
        $image->delete();
        $flashMessage = [
            'heading'=>'success',
            'type'=>'success',
            'message'=>'Image deleted successfully.'
        ];
        \Session::flash('flash_message', $flashMessage);
        return 's';
    }
}

resources/views/gallery/index.blade.php
@extends('layouts.app')
@section('css')
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/Magnific-Popup-master/dist/magnific-popup.css') }}" rel="stylesheet">
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/css/dropify.min.css') }}" rel="stylesheet">

@endsection
@section('page_title')
	Listing Gallery
@endsection
@section('right_button')
    <a href="#add" class="btn btn-info btn-outline pull-right" data-toggle="modal" ><i class="fa fa-plus"></i>&nbsp;Create new gallery</a>
@stop

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="white-box">

			{{-- <div class="row">
				<div class="col-md-12">
					<a href="" class="btn btn-link pull-right">
						<i class="fa fa-trash text-danger">&nbsp;Trash (<span id="getTrashSize"></span>) </i>
					</a>
				</div>
			</div> --}}
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12">
					@if($gallery->count()>0)
					@foreach($gallery as $value)
                    <div class="steamline">
                        <div class="sl-item">
                            <a href="{{ route('profile.view',$value->user->id) }}" class="text-primary">
                                <div class="sl-left bg-info">
                                    <i class="fa fa-image"></i>
                                </div>
                            </a>
                            <div class="sl-right">
                                    <h4>
	                                    <a href="{{ route('gallery.view',$value->id) }}" class="text-primary">{{ $value->gallery_name }} [ {{ count($value->images) }} images ]</a>
	                                    <sup><a href="#deleteGallery" data-toggle="modal" data-ids="{{ $value->id }}" class="text-sm text-danger">Delete</a></sup>
                                    </h4>
                                <div class="desc">
                                	<div>
	                                	<a href="{{ route('profile.view',$value->user->id) }}">
		                                	@if(!empty($value->user->first_name) AND !empty($value->user->last_name))
		                                		<span class="text-primary">{{ $value->user->first_name }} {{ $value->user->last_name }}</span>
		                                	@else
		                                		{{ $value->user->email }}
		                                	@endif
	                                	</a> 
	                                	<span class="sl-date">{{ $value->created_at->diffForHumans() }}</span>
                                	</div>
                                </div>
                                <div class="row inline-photos">
                                	@if ($value->image->count()>0)
		                                @foreach($value->image as $val)
			                                <div class="col-xs-3">
				                                <img class="img-responsive" alt="user" src="{{ asset(STATIC_DIR.'storage/'.$val->image_name) }}">
			                                </div>
		                                @endforeach
									@else
										<p>No Images found</p>
                                	@endif
                                    <div class="col-xs-3" style="margin-top: 30px;">
                                    	<div class="row">
	                                    	<div class="col-md-12">
	                                    		<a href="#addImage" class="btn btn-link btn-sm text-primary" data-toggle="modal" data-ids="{{ $value->id }}">Add image</a>
	                                    	</div>
                                    	</div>
                                    	<div class="row">
                                  			<div class="col-md-12">
                                  				<a href="{{ route('gallery.view',$value->id) }}" class="btn btn-link btn-sm text-primary">View all</a>
                                  			</div>
                                    	</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
					@else
						<p>No items found <a href="#add" class="btn btn-link btn-sm" data-toggle="modal" >&nbsp;Create new</a></p>
                    @endif
	            </div>
			</div>

		</div>
	</div>
</div>
	
@include('gallery.modal')
@endsection

@section('scripts')
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/Magnific-Popup-master/dist/jquery.magnific-popup.min.js') }}"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/Magnific-Popup-master/dist/jquery.magnific-popup-init.js') }}"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/js/dropify.min.js') }}"></script>
	<script>
		 // ADD IMAGE
        $('#addImage').on('show.bs.modal', function (e) {
            var button = $(e.relatedTarget);
            var id = button.data('ids');
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-footer #confirm').data('form', form);
            $("#gallery_id").val(id);
        });

        $(document).ready(function (e) {
		    $('#imageUploadForm').on('submit',(function(e) {
		        e.preventDefault();
		        var formData = new FormData(this);
		        $.ajax({
		            type:'POST',
		            headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') },
		            url: $(this).attr('action'),
		            data:formData,
		            cache:false,
		            contentType: false,
		            processData: false,
		            success:function(data){
		                window.location.reload();
		               //  $('#gallery').fadeOut( function(){
			              //   $('#gallery').fadeIn();
			              // });
		            },
		            error: function(data){
		                console.log("error");
		                console.log(data);
		            }
		        });
		    }));
		});

		 // AJAX GALLERY DELETE
        $('#deleteGallery').on('show.bs.modal', function (e) {
            //e.preventDefault();
            var button = $(e.relatedTarget);
            // console.log(button.data('ids'));
            var ids = button.data('ids');
            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-footer #confirm').data('form', form);
            $("#hidden_id").val(ids);
        });

        $('#deleteGallery').find('.modal-footer #confirm_yes').on('click', function () {
            //$(this).data('form').submit();
            var id = $("#hidden_id").val();
            // console.log(id);
            $.ajax({
                type: "POST",
                url: "{{ route('gallery.delete_gallery') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + id,
                success: function (msg) {
                    // console.log(msg);
                    $("#confirmDelete").modal("hide");
                    window.location.reload();
                }
            });
        });
		
	</script>
@endsection

resources/views/gallery/modal.blade.php
{{--DELETE GALLERY MODAL--}}
<div class="modal fade bs-modal-sm" id="deleteGallery" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Delete Permanently
				</h4>
			</div>
			<div class="modal-body"> Do you want to delete this gallery?</div>
			<input type="hidden" id="hidden_id">
			<div class="modal-footer">
				<button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
				</button>
				<button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
					No
				</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
</div>

{{--ADD FORM--}}
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
	<div class="modal-dialog" role="document">
		<form action="{{ route('gallery.add') }}" method="post" enctype="multipart/form-data">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="exampleModalLabel1"><i class="fa fa-plus-circle" id="icon-terminate" ></i> Create new gallery</h4> </div>
			<div class="modal-body">
				@csrf
				<div class="form-group @if ($errors->has('gallery_name')) has-error @endif">
					<label for="gallery_name" class="control-label">Title:</label>
					<input type="text" class="form-control" name="gallery_name" placeholder="Enter gallery name here" value="{{ old('gallery_name') }}">
					@if ($errors->has('gallery_name'))
						<span class="text-danger" role="alert">
							<p>{{ $errors->first('gallery_name') }}</p>
						</span>
					@endif
				</div>
				<div class="form-group">
					<label for="message-text" class="control-label">Description:</label>
					<textarea class="form-control" rows="5" id="message-text1" name="description" placeholder="Enter description here">{{ old('description') }}</textarea>
					@if ($errors->has('description'))
						<span class="text-danger" role="alert">
							<p>{{ $errors->first('description') }}</p>
						</span>
					@endif
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-outline btn-sm" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-success btn-outline btn-sm" id="confirm_yes"><i class="icon-check"></i> Save</button>
			</div>
		</div>
		</form>
	</div>
</div>

{{--ADD IMAGE FORM--}}
<div class="modal fade" id="addImage" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
	<div class="modal-dialog" role="document">
		<form action="{{ route('gallery.image.add') }}" method="post" enctype="multipart/form-data">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="exampleModalLabel1"><i class="fa fa-plus-circle" id="icon-terminate" ></i> Add Image</h4> </div>
			<div class="modal-body">
				@csrf
				<input type="hidden" name="gallery_id" id="gallery_id">
				<div class="form-group @if ($errors->has('image')) has-error @endif">
					<label for="image" class="control-label"> Image:</label>
					<input type="file" class="form-control-file" name="image[]" multiple accept=".jpg,.png,.bmp,.jpeg">
					@if ($errors->has('image'))
						<span class="text-danger" role="alert">
							<p>{{ $errors->first('image') }}</p>
						</span>
					@endif
					<p style="font-style: italic;color: darkorange;">Appropriate file type: .jpg .jpeg .png</p>
				</div>				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-outline btn-sm" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-success btn-outline btn-sm" id="confirm_yes">Upload</button>
			</div>
		</div>
		</form>
	</div>
</div>

{{--EDIT GALLERY FORM--}}
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
	<div class="modal-dialog" role="document">
		<form action="{{ route('gallery.edit') }}" method="post" enctype="multipart/form-data">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="exampleModalLabel1"><i class="fa fa-plus-circle" id="icon-terminate" ></i> Edit Gallery</h4> </div>
			<div class="modal-body">
				@csrf
				<input type="hidden" name="gallery_id" id="id">
				<div class="form-group @if ($errors->has('title')) has-error @endif">
					<label for="title" class="control-label">Title:</label>
					<input type="text" id="gallery_name" class="form-control" name="gallery_name" placeholder="Enter title here" value="{{ old('title') }}">
					@if ($errors->has('title'))
						<span class="text-danger" role="alert">
							<p>{{ $errors->first('title') }}</p>
						</span>
					@endif
				</div>
				<div class="form-group">
					<label for="message-text" class="control-label">Description:</label>
					<textarea class="form-control" id="description" rows="5" id="message-text1" name="description" placeholder="Enter description here">{{ old('description') }}</textarea>
					@if ($errors->has('description'))
						<span class="text-danger" role="alert">
							<p>{{ $errors->first('description') }}</p>
						</span>
					@endif
				</div>	
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-outline btn-sm" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-success btn-outline btn-sm" id="confirm_yes">Update</button>
			</div>
		</div>
		</form>
	</div>
</div>



{{--DELETE IMAGE MODAL--}}
<div class="modal fade bs-modal-sm" id="confirmDeleteImage" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i>&nbsp;Delete
				</h4>
			</div>
			<div class="modal-body">Delete this Image? </div>
			<input type="hidden" id="hidden_image_id">
			<div class="modal-footer">
				<button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
				</button>
				<button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
					No
				</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
</div>