routes/web.php
    Route::post('/delete', ['uses'=>'Auth\RegisterController@delete', 'as'=>'delete'])->middleware('can:user-delete');
});

Route::group(['prefix' =>ROOT_DIR.'permission', 'middleware' => 'auth', 'as' => 'permission.'], function () {
    Route::get('/list', ['uses'=>'PermissionController@index','as'=>'index'])->middleware('can:permission-add');
    Route::post('/add', ['uses'=>'PermissionController@create','as'=>'add'])->middleware('can:permission-add');
    Route::post('/delete', ['uses'=>'PermissionController@delete','as'=>'delete'])->middleware('can:permission-add');
});

Route::group(['prefix' =>ROOT_DIR.'setting', 'middleware' => 'auth', 'as' => 'setting.'], function () {
    Route::get('/list', ['uses'=>'SettingController@index', 'as'=>'index'])->middleware('can:setting-list');
    Route::post('/store_max_image_size', ['uses'=>'SettingController@store_max_image_size', 'as'=>'store_max_image_size'])->middleware('can:setting-change');
    Route::post('/store_max_file_size', ['uses'=>'SettingController@store_max_file_size', 'as'=>'store_max_file_size'])->middleware('can:setting-change');
    Route::post('/logo', ['uses'=>'SettingController@store_logo', 'as'=>'store_logo'])->middleware('can:setting-change');
    Route::post('/contact_info', ['uses'=>'SettingController@store_contact_info', 'as'=>'contact_info'])->middleware('can:setting-change');
});

Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => 'auth', 'as' => 'profile.'], function () {
    Route::get('/view/{id}', ['uses'=>'ProfileController@view','as'=>'view']);
    Route::post('/update/{type}', ['uses'=>'ProfileController@update','as'=>'update']);
});

Route::group(['prefix' =>ROOT_DIR.'slider', 'middleware' => 'auth', 'as' => 'slider.'], function () {
    Route::get('/list', ['uses'=>'SliderController@index','as'=>'index'])->middleware('can:slider-list');
    Route::post('/add', ['uses'=>'SliderController@create','as'=>'add'])->middleware('can:slider-add');
    Route::get('/edit/{slider_id}', ['uses'=>'SliderController@edit','as'=>'edit'])->middleware('can:slider-add');
    Route::post('/update', ['uses'=>'SliderController@update','as'=>'update'])->middleware('can:slider-add');
    Route::get('/activate/{id}/{action}', ['uses'=>'SliderController@set_active','as'=>'activate'])->middleware('can:slider-add');
    Route::post('/delete', ['uses'=>'SliderController@delete','as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'pages', 'middleware' => 'auth', 'as' => 'pages.'], function () {
    Route::get('/list', ['uses'=>'PostController@index','as'=>'index'])->middleware('can:pages-list');
    Route::get('/add', ['uses'=>'PostController@create','as'=>'add'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'PostController@store'])->middleware('can:pages-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@edit', 'as'=> 'edit'])->middleware('can:pages-edit');
    Route::post('/update', ['uses'=>'PostController@update', 'as'=> 'update'])->middleware('can:pages-edit');
    Route::post('/create_url', ['uses'=>'PostController@create_url', 'as'=>'create_url'])->middleware('can:pages-add');
    Route::post('/recycle', ['uses'=>'PostController@recycle', 'as'=>'recycle'])->middleware('can:pages-delete');
    Route::post('/make_featured', ['uses'=>'PostController@make_featured', 'as'=>'make_featured']);
});

Route::group(['prefix' =>ROOT_DIR.'menu', 'middleware' => 'auth', 'as' => 'menu.'], function () {
    Route::get('/list', ['uses'=>'MenuController@index','as'=>'index'])->middleware('can:menu-list');
    Route::post('/add', ['uses'=>'MenuController@create','as'=>'add'])->middleware('can:menu-add');
    Route::post('/change', ['uses'=>'MenuController@change','as'=>'change'])->middleware('can:menu-add');
    Route::get('/remove_item/{menu_post_id}', ['uses'=>'MenuController@remove_item','as'=>'remove_item'])->middleware('can:menu-add');
    Route::post('/edit_menu', ['uses'=>'MenuController@edit_menu','as'=>'edit_menu'])->middleware('can:menu-add');
    Route::post('/saveOrder', ['uses'=>'MenuController@saveOrder','as'=>'saveOrder'])->middleware('can:menu-add');
    Route::get('/change_status/{menu_id}/{action}', ['uses'=>'MenuController@change_status','as'=>'change_status'])->middleware('can:menu-add');
});

Route::group(['prefix' =>ROOT_DIR.'gallery', 'middleware' => 'auth', 'as' => 'gallery.'], function () {
    Route::get('/list', ['uses'=>'GalleryController@index','as'=>'index'])->middleware('can:gallery-list');
    Route::post('/add', ['uses'=>'GalleryController@create','as'=>'add'])->middleware('can:gallery-add');
    Route::get('/view/{id}', ['uses'=>'GalleryController@display','as'=>'view'])->middleware('can:gallery-list');
    Route::post('/edit', ['uses'=>'GalleryController@edit','as'=>'edit'])->middleware('can:gallery-edit');
    Route::post('/delete_gallery', ['uses'=>'GalleryController@delete_gallery','as'=>'delete_gallery'])->middleware('can:gallery-delete');
    Route::group(['prefix' =>'image', 'middleware' => 'auth', 'as' => 'image.'], function () {
        Route::post('/add', ['uses'=>'GalleryController@add_image','as'=>'add'])->middleware('can:gallery-edit');
        Route::post('/delete', ['uses'=>'GalleryController@delete_image','as'=>'delete'])->middleware('can:gallery-delete');
    });
});

Route::group(['prefix' =>ROOT_DIR.'category', 'middleware' => 'auth', 'as' => 'category.'], function () {
    Route::get('/list', ['uses'=>'CategoryController@index','as'=>'index'])->middleware('can:category-list');
    Route::get('/list_item/{id}', ['uses'=>'CategoryController@list_item','as'=>'list_item'])->middleware('can:category-list');
    Route::post('/store', ['uses'=>'CategoryController@store', 'as'=>'store'])->middleware('can:category-add');
    Route::post('/delete', ['uses'=>'CategoryController@delete_category','as'=>'delete'])->middleware('can:category-list');
    Route::post('/update', ['uses'=>'CategoryController@update_category','as'=>'update'])->middleware('can:category-list');

    // Items
    Route::get('/add_item/{category_id}', ['uses'=>'CategoryController@add_item', 'as'=>'add_item'])->middleware('can:category-add');
    Route::post('/store_item', ['uses'=>'CategoryController@store_item', 'as'=>'store_item'])->middleware('can:category-add');
    Route::post('/update_item', ['uses'=>'CategoryController@update_item', 'as'=>'update_item'])->middleware('can:category-add');
    Route::get('/edit_item/{item_id}', ['uses'=>'CategoryController@edit_item', 'as'=>'edit_item'])->middleware('can:category-add');
    Route::post('/delete_item', ['uses'=>'CategoryController@delete_item', 'as'=>'delete_item'])->middleware('can:category-add');
});

Route::group(['prefix' =>ROOT_DIR.'downloads', 'middleware' => 'auth', 'as' => 'downloads.'], function () {
    Route::get('/list', ['uses'=>'DownloadController@index', 'as'=>'index'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'DownloadController@store', 'as'=>'add'])->middleware('can:pages-add');
    Route::post('/edit', ['uses'=>'DownloadController@edit', 'as'=>'edit'])->middleware('can:pages-add');
    Route::post('/delete', ['uses'=>'DownloadController@delete', 'as'=>'delete'])->middleware('can:pages-add');
    Route::get('/download/{id}', ['uses'=>'DownloadController@download', 'as'=>'download'])->middleware('can:pages-add');
    Route::group(['prefix' =>'item', 'middleware' => 'auth', 'as' => 'item.'], function () {
        Route::get('/view_item/{id}', ['uses'=>'DownloadController@view_item', 'as'=>'view_item'])->middleware('can:pages-add');
        Route::post('/add', ['uses'=>'DownloadController@store_item', 'as'=>'add'])->middleware('can:pages-add');
        Route::post('/delete', ['uses'=>'DownloadController@delete_item', 'as'=>'delete'])->middleware('can:pages-add');
    });
});

// post route
Route::group(['prefix' =>ROOT_DIR.'post', 'middleware' => 'auth', 'as' => 'post.'], function () {
    Route::get('/list', ['uses'=>'PostController@get_post_index','as'=>'index'])->middleware('can:post-list');
    Route::get('/add', ['uses'=>'PostController@get_post_create','as'=>'add'])->middleware('can:post-add');
    Route::post('/add', ['uses'=>'PostController@post_store'])->middleware('can:post-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@get_post_edit', 'as'=> 'edit'])->middleware('can:post-add');
    Route::post('/update', ['uses'=>'PostController@post_update', 'as'=> 'update'])->middleware('can:post-add');
    Route::post('/recycle', ['uses'=>'PostController@post_recycle', 'as'=>'recycle'])->middleware('can:post-add');
});

// weblink route
Route::group(['prefix' =>ROOT_DIR.'weblink', 'middleware' => 'auth', 'as' => 'weblink.'], function () {
    Route::get('/list', ['uses'=>'WeblinkController@index','as'=>'index'])->middleware('can:weblink-list');
    Route::post('/add', ['uses'=>'WeblinkController@store','as'=>'add'])->middleware('can:weblink-add');
    Route::post('/delete', ['uses'=>'WeblinkController@delete','as'=>'delete'])->middleware('can:weblink-delete');
    // items
    Route::get('/view/{weblink_id}', ['uses'=>'WeblinkController@display','as'=>'view'])->middleware('can:weblink-item-list');
    Route::post('/item/update', ['uses'=>'WeblinkController@updateItem','as'=>'item.update'])->middleware('can:weblink-item-edit');
    Route::post('/item/addPost', ['uses'=>'WeblinkController@addPost','as'=>'item.addPost'])->middleware('can:weblink-item-add');
    Route::get('/item/remove/{weblink_post_id}', ['uses'=>'WeblinkController@removeItem','as'=>'item.remove'])->middleware('can:weblink-item-delete');
});

// job portal
Route::group(['prefix' =>ROOT_DIR.'jobs', 'middleware' => 'auth', 'as' => 'jobs.'], function () {
    Route::get('/list', ['uses'=>'JobController@index','as'=>'index'])->middleware('can:jobs-list');
    Route::get('/add', ['uses'=>'JobController@create','as'=>'add'])->middleware('can:jobs-add');
    Route::post('/add', ['uses'=>'JobController@store'])->middleware('can:jobs-add');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    
    // public function post()
    // {
    // 	return $this->hasMany('App\Post','created_by');
    // }
}

resources/views/menu/index.blade.php
@extends('layouts.app')
@section('css')
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/nestable/nestable.css') }}" rel="stylesheet" type="text/css" />
	<style>
		.myadmin-dd-empty .dd-list button {
			width: auto;
			height: auto;
			font-size: 12px;
			margin-top: 12px;
		}
		.checkbox label::before {
			border-radius: 2px;
			border: 1px solid #c5c5c5;
		}
		div.disabled{
			pointer-events: none;
			opacity: 0.5;
			background: #CCC;
		}
		.collapsible {
			cursor: pointer;
			padding-right: 20px;
			border: none;
		}
		.content {
			padding-top: 20px;
			display: none;
			overflow: hidden;
		}
	</style>
@endsection
@section('page_title')
	List menu
@endsection
@section('right_button')
@stop

@section('content')
	<!--SELECT MENU START-->
	<form action="{{ route('menu.change') }}" method="post">
		<div class="row">
			<div class="col-md-12">
				<div class="white-box">
					<h3 class="box-title">Select a menu to edit</h3>
					@csrf
					<div class="row">
						@if(!empty($menus))
							<div class="col-md-6 {{ $errors->has('menu_id_change') ? 'has-error' : '' }}">
								<select name="menu_id_change" id="" class="form-control" >
									<option value="">--Select Menu--</option>
									@foreach($menus as $val)
										<option @if(isset($selected_menu)) @if($val->id==$selected_menu->id) selected @endif @endif value="{{ $val->id }}">{{ $val->title }}</option>
									@endforeach
								</select>
								@if ($errors->has('menu_id_change'))
									<span class="text-danger text-sm-left" role="alert">
                                		<small>{{ $errors->first('menu_id_change') }}</small>
                            		</span>
								@endif
							</div>
							<div class="col-md-6">
								<button type="submit" name="action" value="select_menu" class="btn btn-success btn-outline btn-sm">Select</button>
								&nbsp;&nbsp;or<a class="btn btn-link btn-sm" href="#add" data-toggle="modal">Create a new menu</a>
							</div>
						@else
							<div class="col-md-12">
								<a href="" class="btn btn-link btn-sm">Create a new menu</a>
							</div>
						@endif
					</div>
				</div>
			</div>
		</div>
	</form>
	<!--SELECT MENU END-->
	
	<div class="row @if(empty($selected_menu)) disabled @endif">
		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" >
			<!--ADD PAGES START-->
			<form action="{{ route('menu.change') }}" method="post">
				@csrf
				<input type="hidden" name="selected_menu_id" id="" value="{{ $selected_menu->id ?? '' }}">
				<div class="panel panel-default">
					<div class="panel-heading">Pages</div>
					<div class="panel-wrapper collapse in" >
						<div class="panel-body" style="padding-top: 2px;padding-bottom: 25px !important;height:200px;overflow-y: scroll;">
							@if(isset($pages))
								@foreach($pages as $val)
									<div class="checkbox checkbox-custom">
										<input id="checkbox11" type="checkbox" name="page_id[]" multiple="" value="{{ $val->id }}">
										<label for="checkbox11"> {{ $val->post_title }} </label>
									</div>
								@endforeach
							@else
								<p>No pages found. <a href="" class="btn btn-link btn-sm">Create a new page</a></p>
							@endif
						</div>
						<div class="panel-footer" style="padding-top: 5px;padding-bottom: 35px;">
							<button class="btn btn-success btn-outline pull-right btn-sm" name="action" value="add_pages">Add to menu</button>
						</div>
					</div>
				</div>
			</form>
			<!--ADD PAGES END-->
			
			<!--ADD LINK START-->
			<form action="{{ route('menu.change') }}" method="post">
				@csrf
				<input type="hidden" name="selected_menu_id" id="" value="{{ $selected_menu->id ?? '' }}">
				<div class="panel panel-default">
					<div class="panel-heading">Add custom link</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body" style="padding-bottom: 5px !important;">
							<div class="form-group">
								<label for="link_name">Name</label>
								<input id="link_name" type="text" class="form-control" name="link_name">
							</div>
							<div class="form-group">
								<label for="name">Link</label>
								<input id="link" type="text" class="form-control" name="custom_link" value="https://">
							</div>
							<button class="btn btn-success btn-outline btn-sm pull-right" name="action" value="add_link">Add to menu</button>
						</div>
						{{--<div class="panel-footer"> Add custom link </div>--}}
					</div>
				</div>
			</form>
			<!--ADD LINK END-->

			<!--ADD DOWNLOADS START-->
			<form action="{{ route('menu.change') }}" method="post">
				@csrf
				<input type="hidden" name="selected_menu_id" id="" value="{{ $selected_menu->id ?? '' }}">
				<div class="panel panel-default">
					<div class="panel-heading">Downloads</div>
					<div class="panel-wrapper collapse in" >
						<div class="panel-body" style="padding-top: 2px;padding-bottom: 25px !important;height:200px;overflow-y: scroll;">
							@if($downloads->count()>0)
								@foreach($downloads as $val)
									<div class="checkbox checkbox-custom">
										<input id="checkbox11" type="checkbox" name="downloads_id[]" multiple="" value="{{ $val->downloads_category_id }}">
										<label for="checkbox11"> {{ $val->title }} </label>
									</div>
								@endforeach
							@else
								<p>No downloads found. <a href="{{ route('downloads.index') }}" class="btn btn-link btn-sm">Create new</a></p>
							@endif
						</div>
						<div class="panel-footer" style="padding-top: 5px;padding-bottom: 35px;">
							<button class="btn pull-right btn-success btn-outline btn-sm" name="action" value="add_downloads">Add to menu</button>
						</div>
					</div>
				</div>
			</form>
			<!--ADD DOWNLOADS END-->
		</div>
		
		<!--MENU NESTABLE START-->
		<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
			<div class="panel panel-default">
				<form action="{{ route('menu.change') }}" method="post">
					@csrf
					<input type="hidden" name="selected_menu_id" id="" value="{{ $selected_menu->id ?? '' }}">
					<div class="panel-heading">
						Menu structure
						@if (isset($selected_menu))
							@if ($selected_menu->is_active==1)
								<span class="badge badge-success">Active</span> <sup><a href="{{ route('menu.change_status',[$selected_menu->id,'deactivate']) }}" class="text-danger">Deactivate?</a></sup>
							@else
								<span class="badge badge-danger">Inactive</span> <sup><a href="{{ route('menu.change_status',[$selected_menu->id,'activate']) }}" class="text-success">Activate?</a></sup>
							@endif
						@endif
						<hr>
						<div class="row">
							<div class="col-md-6 {{ $errors->has('menu_title') ? 'has-error' : '' }}">
								<input type="text" name="menu_title" class="form-control" id="" value="{{ $selected_menu->title ?? '' }}">
								@if ($errors->has('menu_title'))
									<span class="text-danger text-sm-left" role="alert">
                                		<small>{{ $errors->first('menu_title') }}</small>
                            		</span>
								@endif
								<input type="hidden" name="selected_menu_id" id="" value="{{ $selected_menu->id ?? '' }}">
							</div>
							<div class="col-md-6">
								<button type="submit" name="action" value="save_menu_name" class="btn btn-success btn-outline btn-sm"><i class="icon-check"></i> Save</button>
							</div>
						</div>
					</div>
				</form>
				@include('menu.menu')
			</div>
		</div>
		<!--MENU NESTABLE END-->
	</div>
	
	<!--SET MENU DEPTH-->
	<input type="hidden" id="menu_type" value="{{ $selected_menu->menu_type ?? '' }}">
	<!--SET MENU DEPTH END-->
	@include('menu.model')
@endsection

@section('scripts')
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/nestable/jquery.nestable.js') }}"></script>
	<script type="text/javascript">
        $(document).ready(function() {
            // Nestable
            // var updateOutput = function(e) {
            //     var list = e.length ? e : $(e.target),
            //         output = list.data('output');
            //
            // };
            $('#nestable2').on('click', function(e) {
                var target = $(e.target),
                    action = target.data('action');
                if (action === 'expand-all') {
                    $('.dd').nestable('expandAll');
                }
                if (action === 'collapse-all') {
                    $('.dd').nestable('collapseAll');
                }
            });
            
            // SETTING MENU DEPTH
	        var menuType = $('#menu_type').val();
	        var depth = 0;
	        switch (menuType) {
                case 'nav_menu':
                    depth = 3;
                    break;
                case 'prenav_menu':
                    depth = 1;
                    break;
                case 'footer_menu':
                    depth = 1;
                    break;
                default:
                    depth = 3;
            }
            
            $('#nestable2').nestable({maxDepth:depth});
            
            
            $('#saveMenuOrder').on('click', function(){
                $.ajax({
                    type: "POST",
                    url: "{{ route('menu.saveOrder') }}",
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: {data:$('.dd').nestable('serialize')},
                    success: function (msg) {
                        console.log(msg);
                        // $("#confirmDelete").modal("hide");
                        window.location.reload();
                    }
                });
            });
        });

        // ADD MENU
        // $('#add').find('.modal-footer #confirm_yes').on('click', function (e) {
        // 	e.preventDefault();
        //     $("#confirmDelete").modal("hide");
        //     window.location.reload();
        //
        // });
        //
        // var clickData = {};
	</script>
	<script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                    content.style.display = "none";
                } else {
                    content.style.display = "block";
                }
            });
        }
	</script>
@endsection

resources/views/menu/menu.blade.php
<div class="panel-wrapper collapse in" aria-expanded="true">
	<div class="panel-body">
		<h3 class="box-title">{{ $selected_menu->title ?? '' }}
			[&nbsp;<span class="text-blue">
                                @if(isset($selected_menu))
					@if($selected_menu->menu_type=='nav_menu')
						Navigation Menu
					@elseif($selected_menu->menu_type=='prenav_menu')
						Pre Navigation Menu
					@elseif($selected_menu->menu_type=='footer_menu')
						Footer Menu
					@endif
				@endif
                            </span>&nbsp;]
		</h3>
		<div class="dd myadmin-dd-empty" id="nestable2">
			<ol class="dd-list">
				@if(isset($selected_menu_item))
					@foreach($selected_menu_item as $value)
						<li class="dd-item dd3-item" data-id="{{ $value->menu_post_id }}">
							<div class="dd-handle dd3-handle"></div>
							<div class="dd3-content">
								<form action="{{ route('menu.edit_menu') }}" method="post">
									@csrf
									{{ $value->menu_display_name ?? $value->post->post_title }}
									<span style="font-weight: lighter; padding-left: 20px;font-style: italic;">
														@if($value->post->post_type=='page')
											<span>page</span>
										@elseif($value->post->post_type=='custom_link')
											<span>Custom Link</span>
										@else
											<span></span>
										@endif
								                    </span>
									<a class="link" href="{{ route('menu.remove_item',$value->menu_post_id) }}">
										<i class="mdi mdi-close text-danger pull-right"></i>
									</a>
									<a class="collapsible pull-right"><i id="menu-edit-icon" class="fa fa-caret-down"></i></a>
									<div class="content">
										@include('menu.editMenuForm')
									</div>
								</form>
							</div>
							{{--CHILD MENU START--}}
							@if ($value->children->count())
								@include('menu.menuChild')
							@endif
							{{--CHILD MENU END--}}
						</li>
					@endforeach
				@else
					<p>No items found. App pages</p>
				@endif
			</ol>
		</div>
	</div>
	<div class="panel-footer">
		MENU STRUCTURE
		<button id="saveMenuOrder" type="button" class="btn btn-success btn-outline btn-sm pull-right">Save Order</button>
	</div>
</div>

resources/views/menu/menuChild.blade.php
<ol class="dd-list">
	@foreach($value->children as $child)
		{{--{{dd($child)}}--}}
		<li class="dd-item dd3-item" data-id="{{ $child->menu_post_id }}">
			<div class="dd-handle dd3-handle"></div>
			<div class="dd3-content">
				<form action="{{ route('menu.edit_menu') }}" method="post">
					@csrf
					{{ $child->menu_display_name ?? $child->post->post_title }}
					<span style="font-weight: lighter; padding-left: 20px;font-style: italic;">
													                    @if($child->post->post_type=='page')
							<span>page</span>
						@elseif($child->post->post_type=='custom_link')
							<span>Custom Link</span>
						@else
							<span></span>
						@endif
											                        </span>
					<a class="link" href="{{ route('menu.remove_item',$child->menu_post_id) }}">
						<i class="mdi mdi-close text-danger pull-right"></i>
					</a>
					<a class="collapsible pull-right">
						<i id="menu-edit-icon" class="fa fa-caret-down"></i>
					</a>
					<div class="content">
						@include('menu.editMenuFormChild')
					</div>
				</form>
			</div>
			@if ($child->children->count())
				@include('menu.menuSubchild')
			@endif
		</li>
	@endforeach
</ol>

resources/views/menu/menuSubchild.blade.php
<ol class="dd-list">
	@foreach($child->children as $subchild)
		<li class="dd-item dd3-item" data-id="{!! $subchild->menu_post_id !!}">
			<div class="dd-handle dd3-handle"></div>
			<div class="dd3-content">
				<form action="{{ route('menu.edit_menu') }}" method="post">
					@csrf
					{!! $subchild->menu_display_name ?? $subchild->post->post_title !!}
					<span style="font-weight: lighter; padding-left: 20px;font-style: italic;">
																                        @if($subchild->post->post_type=='page')
							<span>page</span>
						@elseif($subchild->post->post_type=='custom_link')
							<span>Custom Link</span>
						@else
							<span></span>
						@endif
														                            </span>
					<a class="link" href="{{ route('menu.remove_item',$subchild->menu_post_id) }}">
						<i class="mdi mdi-close text-danger pull-right"></i>
					</a>
					<a class="collapsible pull-right">
						<i id="menu-edit-icon" class="fa fa-caret-down"></i>
					</a>
					<div class="content">
						@include('menu.editMenuFormSubchild')
					</div>
				</form>
			</div>
		</li>
	@endforeach
</ol>

resources/views/menu/model.blade.php
<div class="modal fade bs-modal-sm" id="add" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title"><i class="fa fa-plus-circle" id="icon-terminate" ></i> Create new menu
				</h4>
			</div>
			<form action="{{ route('menu.add') }}" method="post">
				@csrf
				<div class="modal-body">
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Menu name') }}</label>
						<div class="col-md-6">
							<input id="name" type="text" class="form-control" name="title" value="{{ old('title') }}"  placeholder="Enter menu name" required autofocus>

							@if ($errors->has('title'))
								<span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
							@endif
							<p style="font-style: italic;color: darkorange;">Example: Main menu</p>
						</div>
					</div>
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Menu type') }}</label>
						<div class="col-md-6">
							<select class="form-control" required="" name="menu_type">
                                <option value="">--Select menu type--</option>
                                <option value="prenav_menu">Pre Navigation</option>
                                <option value="nav_menu">Navigation</option>
                                <option value="footer_menu">Footer</option>
                            </select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-success btn-outline btn-sm confirm_yes" id="confirm_yes"><i class="icon-check"></i> Save
					</button>
					<button type="button" class="pull-left btn btn-default btn-sm btn-outline" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
						close
					</button>
				</div>
			</form>
		</div>
		<!-- /.modal-content -->
	</div>
</div>