routes/web.php
<?php

//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','admin/');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','assets/icons/default-user.png');
if(!defined('DEFAULT_IMAGE')) define('DEFAULT_IMAGE','assets/icons/default-image.png');
if(!defined('LOGO_DARK')) define('LOGO_DARK','assets/icons/delta-dark.png');
if(!defined('LOGO_WHITE')) define('LOGO_WHITE','assets/icons/delta-white.png');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * BACK END ROUTES
 */
Route::get(ROOT_DIR.'login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post(ROOT_DIR.'login', 'Auth\LoginController@login');
Route::post(ROOT_DIR.'logout', 'Auth\LoginController@logout')->name('logout');
Route::post(ROOT_DIR.'password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get(ROOT_DIR.'password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post(ROOT_DIR.'password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get(ROOT_DIR.'password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get(ROOT_DIR, 'HomeController@index')->name('home');

Route::group(['prefix' =>ROOT_DIR.'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
    Route::get('/register', ['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register'])->middleware('can:user-add');
    Route::post('/register', 'Auth\RegisterController@register')->middleware('can:user-add');
    Route::get('/edit/{id}', ['uses'=>'Auth\RegisterController@showEditForm','as'=>'edit'])->middleware('can:user-edit');
    Route::post('/update', ['uses'=>'Auth\RegisterController@update','as'=> 'update'])->middleware('can:user-edit');
    Route::get('/list', ['uses'=>'Auth\RegisterController@index', 'as'=>'index'])->middleware('can:user-list');
    Route::post('/permission_view', ['uses'=>'PermissionController@permission_view', 'as'=>'permission_view']);
    Route::get('/assign_permission/{id}', ['uses'=>'PermissionController@assign_permission', 'as'=>'assign_permission'])->middleware('can:user-permission-assign');
    Route::post('/assign_permission/store', ['uses'=>'PermissionController@assign_permission_store', 'as'=>'assign_permission_store'])->middleware('can:user-permission-assign');
    Route::post('/delete', ['uses'=>'Auth\RegisterController@delete', 'as'=>'delete'])->middleware('can:user-delete');
});

Route::group(['prefix' =>ROOT_DIR.'permission', 'middleware' => 'auth', 'as' => 'permission.'], function () {
    Route::get('/list', ['uses'=>'PermissionController@index','as'=>'index'])->middleware('can:permission-add');
    Route::post('/add', ['uses'=>'PermissionController@create','as'=>'add'])->middleware('can:permission-add');
    Route::post('/delete', ['uses'=>'PermissionController@delete','as'=>'delete'])->middleware('can:permission-add');
});

Route::group(['prefix' =>ROOT_DIR.'setting', 'middleware' => 'auth', 'as' => 'setting.'], function () {
    Route::get('/list', ['uses'=>'SettingController@index', 'as'=>'index'])->middleware('can:setting-list');
    Route::post('/store_max_image_size', ['uses'=>'SettingController@store_max_image_size', 'as'=>'store_max_image_size'])->middleware('can:setting-change');
    Route::post('/store_max_file_size', ['uses'=>'SettingController@store_max_file_size', 'as'=>'store_max_file_size'])->middleware('can:setting-change');
    Route::post('/logo', ['uses'=>'SettingController@store_logo', 'as'=>'store_logo'])->middleware('can:setting-change');
    Route::post('/contact_info', ['uses'=>'SettingController@store_contact_info', 'as'=>'contact_info'])->middleware('can:setting-change');
});

Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => 'auth', 'as' => 'profile.'], function () {
    Route::get('/view/{id}', ['uses'=>'ProfileController@view','as'=>'view']);
    Route::post('/update/{type}', ['uses'=>'ProfileController@update','as'=>'update']);
});

Route::group(['prefix' =>ROOT_DIR.'slider', 'middleware' => 'auth', 'as' => 'slider.'], function () {
    Route::get('/list', ['uses'=>'SliderController@index','as'=>'index'])->middleware('can:slider-list');
    Route::post('/add', ['uses'=>'SliderController@create','as'=>'add'])->middleware('can:slider-add');
    Route::get('/edit/{slider_id}', ['uses'=>'SliderController@edit','as'=>'edit'])->middleware('can:slider-add');
    Route::post('/update', ['uses'=>'SliderController@update','as'=>'update'])->middleware('can:slider-add');
    Route::get('/activate/{id}/{action}', ['uses'=>'SliderController@set_active','as'=>'activate'])->middleware('can:slider-add');
    Route::post('/delete', ['uses'=>'SliderController@delete','as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'pages', 'middleware' => 'auth', 'as' => 'pages.'], function () {
    Route::get('/list', ['uses'=>'PostController@index','as'=>'index'])->middleware('can:pages-list');
    Route::get('/add', ['uses'=>'PostController@create','as'=>'add'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'PostController@store'])->middleware('can:pages-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@edit', 'as'=> 'edit'])->middleware('can:pages-edit');
    Route::post('/update', ['uses'=>'PostController@update', 'as'=> 'update'])->middleware('can:pages-edit');
    Route::post('/create_url', ['uses'=>'PostController@create_url', 'as'=>'create_url'])->middleware('can:pages-add');
    Route::post('/recycle', ['uses'=>'PostController@recycle', 'as'=>'recycle'])->middleware('can:pages-delete');
    Route::post('/make_featured', ['uses'=>'PostController@make_featured', 'as'=>'make_featured']);
});

Route::group(['prefix' =>ROOT_DIR.'menu', 'middleware' => 'auth', 'as' => 'menu.'], function () {
    Route::get('/list', ['uses'=>'MenuController@index','as'=>'index'])->middleware('can:menu-list');
    Route::post('/add', ['uses'=>'MenuController@create','as'=>'add'])->middleware('can:menu-add');
    Route::post('/change', ['uses'=>'MenuController@change','as'=>'change'])->middleware('can:menu-add');
    Route::get('/remove_item/{menu_post_id}', ['uses'=>'MenuController@remove_item','as'=>'remove_item'])->middleware('can:menu-add');
    Route::post('/edit_menu', ['uses'=>'MenuController@edit_menu','as'=>'edit_menu'])->middleware('can:menu-add');
    Route::post('/saveOrder', ['uses'=>'MenuController@saveOrder','as'=>'saveOrder'])->middleware('can:menu-add');
    Route::get('/change_status/{menu_id}/{action}', ['uses'=>'MenuController@change_status','as'=>'change_status'])->middleware('can:menu-add');
});

Route::group(['prefix' =>ROOT_DIR.'gallery', 'middleware' => 'auth', 'as' => 'gallery.'], function () {
    Route::get('/list', ['uses'=>'GalleryController@index','as'=>'index'])->middleware('can:gallery-list');
    Route::post('/add', ['uses'=>'GalleryController@create','as'=>'add'])->middleware('can:gallery-add');
    Route::get('/view/{id}', ['uses'=>'GalleryController@display','as'=>'view'])->middleware('can:gallery-list');
    Route::post('/edit', ['uses'=>'GalleryController@edit','as'=>'edit'])->middleware('can:gallery-edit');
    Route::post('/delete_gallery', ['uses'=>'GalleryController@delete_gallery','as'=>'delete_gallery'])->middleware('can:gallery-delete');
    Route::group(['prefix' =>'image', 'middleware' => 'auth', 'as' => 'image.'], function () {
        Route::post('/add', ['uses'=>'GalleryController@add_image','as'=>'add'])->middleware('can:gallery-edit');
        Route::post('/delete', ['uses'=>'GalleryController@delete_image','as'=>'delete'])->middleware('can:gallery-delete');
    });
});

Route::group(['prefix' =>ROOT_DIR.'category', 'middleware' => 'auth', 'as' => 'category.'], function () {
    Route::get('/list', ['uses'=>'CategoryController@index','as'=>'index'])->middleware('can:category-list');
    Route::get('/list_item/{id}', ['uses'=>'CategoryController@list_item','as'=>'list_item'])->middleware('can:category-list');
    Route::post('/store', ['uses'=>'CategoryController@store', 'as'=>'store'])->middleware('can:category-add');
    Route::post('/delete', ['uses'=>'CategoryController@delete_category','as'=>'delete'])->middleware('can:category-list');
    Route::post('/update', ['uses'=>'CategoryController@update_category','as'=>'update'])->middleware('can:category-list');

    // Items
    Route::get('/add_item/{category_id}', ['uses'=>'CategoryController@add_item', 'as'=>'add_item'])->middleware('can:category-add');
    Route::post('/store_item', ['uses'=>'CategoryController@store_item', 'as'=>'store_item'])->middleware('can:category-add');
    Route::post('/update_item', ['uses'=>'CategoryController@update_item', 'as'=>'update_item'])->middleware('can:category-add');
    Route::get('/edit_item/{item_id}', ['uses'=>'CategoryController@edit_item', 'as'=>'edit_item'])->middleware('can:category-add');
    Route::post('/delete_item', ['uses'=>'CategoryController@delete_item', 'as'=>'delete_item'])->middleware('can:category-add');
});

Route::group(['prefix' =>ROOT_DIR.'downloads', 'middleware' => 'auth', 'as' => 'downloads.'], function () {
    Route::get('/list', ['uses'=>'DownloadController@index', 'as'=>'index'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'DownloadController@store', 'as'=>'add'])->middleware('can:pages-add');
    Route::post('/edit', ['uses'=>'DownloadController@edit', 'as'=>'edit'])->middleware('can:pages-add');

resources/views/pages/index.blade.php
@extends('layouts.app')
@section('css')
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }
        
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }
        
        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }
        
        input:checked + .slider {
            background-color: #2196F3;
        }
        
        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }
        
        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }
        
        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }
        
        .slider.round:before {
            border-radius: 50%;
        }
    </style>
@endsection
@section('page_title')
    All pages
@endsection
@section('right_button')
    <a href="{{ route('pages.add') }}" class="btn btn-block btn-info btn-outline" data-toggle="modal" ><i class="fa fa-plus"></i>&nbsp;Create new page</a>
@stop
@section('content-title')
	<h2>
		All pages
	</h2>

@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('pages.index','trashed=true') }}" class="pull-right btn btn-link btn-sm"><span class="fa fa-trash text-danger"></span>&nbsp;Trash({{ $trash_count }})</a>
            <a href="{{ route('pages.index') }}" class="pull-right btn btn-link btn-sm">List pages</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="table-responsive">
                    <table id="datatable" class="table table-borderless table-striped" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th style="width: 700px;">Page Title</th>
                            <th>Author</th>
	                        <th>Make Featured</th>
	                        <th>Created</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($pages->count()>0)
                            @foreach($pages as $val)
                                <tr class="title">
                                    <td>
                                        {{ $val->post_title }}
                                        @if($val->post_status == 'draft')
                                        <span style="font-style: italic;padding-left: 50px;" class="text-danger">(draft)</span>
                                        @elseif($val->post_status=='publish')
                                        <span class="text-success" style="font-style: italic;padding-left: 50px;">&nbsp;&nbsp;(Published)</span>
                                        @endif
                                        <div class="action">
                                            @if($val->is_trashed==1)
                                                <a class="btn btn-link btn-sm text-success" href="#confirmTrash" data-ids="{{ $val->id }}" data-msg="Do you want to restore this page ?" data-action="restore" data-toggle="modal">Restore</a>
                                                <a class="btn btn-link btn-sm text-danger" href="#confirmTrash" data-ids="{{ $val->id }}" data-msg="Do you want to delete this page ?" data-action="delete" data-toggle="modal">Delete</a>
                                            @else
                                                <a href="{{ route('front_page',$val->post_slug) }}" target="_blank" class="btn btn-link btn-sm">Preview</a>
                                                <span class="vl"></span>
                                                <a href="{{ route('pages.edit',$val->id) }}" class="btn btn-link btn-sm">Edit</a>
                                                <span class="vl"></span>
                                                <a class="btn btn-link btn-sm text-danger" href="#confirmTrash" data-ids="{{ $val->id }}" data-msg="Do you want to move this page to Trash ?" data-action="trash" data-toggle="modal">Trash</a>
											@endif
                                        </div>
                                    </td>
                                    <td><a href="{{ route('profile.view',$val->user->id) }}" calss="btn btn-link btn-sm">{{ $val->user->first_name }} {{ $val->user->last_name }}</a></td>
	                                <td>
		                                <label class="switch">
			                                <input class="feature_switch" type="checkbox" value="{{ $val->id }}" @if($val->is_featured==1) checked @endif>
			                                <span class="slider round"></span>
		                                </label>
	                                </td>
                                    <td>{{ $val->created_at->diffForHumans() }}</td>
	                                
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="3">No items found <a href="{{ route('pages.add') }}" class="btn btn-link btn-sm" data-toggle="modal" >Create new page</a></td>
                            </tr>
                        @endif
                    </table>
                </div>
            </div>
        </div>
    </div>

@include('pages.modal')
@endsection

@section('scripts')
	<script>
        $('#datatable').DataTable({
            dom: 'Bfrtip',
            columnDefs: [ { "orderable": false, "visible": true } ],
        });

        $('#add').find('.modal-footer #confirm_yes').on('click', function () {
            $("#confirmDelete").modal("hide");
            window.location.reload();

        });

        // MOVE TO TRASH
        $('#confirmTrash').on('show.bs.modal', function (e) {
            //e.preventDefault();
            var button = $(e.relatedTarget);
            // console.log(button.data('ids'));
            var ids = button.data('ids');
            var msg = button.data('msg');
            var action = button.data('action');
            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modal-footer #confirm').data('form', form);
            $("#hidden_id").val(ids);
            $("#msg").html(msg);
            $("#action").val(action);
        });

        $('#confirmTrash').find('.modal-footer #confirm_yes').on('click', function () {
            //$(this).data('form').submit();
            var id = $("#hidden_id").val();
            var action = $("#action").val();
            // console.log(id);
            $.ajax({
                type: "POST",
                url: "{{ route('pages.recycle') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: {id: id , action: action},
                success: function (msg) {
                    window.location.reload();
                }
            });
        });
        // AJAX DELETE PERMISSION END
		
		$('.feature_switch').on('change', function(e){
		    var post_id = $(this).val();
            $.ajax({
                type: "POST",
                url: "{{ route('pages.make_featured') }}",
                headers: {
                    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                },
                data: "id=" + post_id,
                success: function (msg) {
                    window.location.reload();
                }
            });
		})
	</script>
@endsection

resources/views/pages/modal.blade.php
{{--DELETE MODAL--}}
<div class="modal fade bs-modal-sm" id="confirmTrash" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i>&nbsp;Move to Trash
				</h4>
			</div>
			<div class="modal-body" id="msg"> </div>
			<input type="hidden" id="hidden_id">
			<input type="hidden" id="action">
			<div class="modal-footer">
				<button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
				</button>
				<button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
					No
				</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
</div>