routes/web.php
<?php

//defines
if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','admin/');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','assets/icons/default-user.png');
if(!defined('DEFAULT_IMAGE')) define('DEFAULT_IMAGE','assets/icons/default-image.png');
if(!defined('LOGO_DARK')) define('LOGO_DARK','assets/icons/delta-dark.png');
if(!defined('LOGO_WHITE')) define('LOGO_WHITE','assets/icons/delta-white.png');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/**
 * BACK END ROUTES
 */
Route::get(ROOT_DIR.'login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post(ROOT_DIR.'login', 'Auth\LoginController@login');
Route::post(ROOT_DIR.'logout', 'Auth\LoginController@logout')->name('logout');
Route::post(ROOT_DIR.'password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get(ROOT_DIR.'password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post(ROOT_DIR.'password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get(ROOT_DIR.'password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get(ROOT_DIR, 'HomeController@index')->name('home');

Route::group(['prefix' =>ROOT_DIR.'user', 'middleware' => 'auth', 'as' => 'user.'], function () {
    Route::get('/register', ['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register'])->middleware('can:user-add');
    Route::post('/register', 'Auth\RegisterController@register')->middleware('can:user-add');
    Route::get('/edit/{id}', ['uses'=>'Auth\RegisterController@showEditForm','as'=>'edit'])->middleware('can:user-edit');
    Route::post('/update', ['uses'=>'Auth\RegisterController@update','as'=> 'update'])->middleware('can:user-edit');
    Route::get('/list', ['uses'=>'Auth\RegisterController@index', 'as'=>'index'])->middleware('can:user-list');
    Route::post('/permission_view', ['uses'=>'PermissionController@permission_view', 'as'=>'permission_view']);
    Route::get('/assign_permission/{id}', ['uses'=>'PermissionController@assign_permission', 'as'=>'assign_permission'])->middleware('can:user-permission-assign');
    Route::post('/assign_permission/store', ['uses'=>'PermissionController@assign_permission_store', 'as'=>'assign_permission_store'])->middleware('can:user-permission-assign');
    Route::post('/delete', ['uses'=>'Auth\RegisterController@delete', 'as'=>'delete'])->middleware('can:user-delete');
});

Route::group(['prefix' =>ROOT_DIR.'permission', 'middleware' => 'auth', 'as' => 'permission.'], function () {
    Route::get('/list', ['uses'=>'PermissionController@index','as'=>'index'])->middleware('can:permission-add');
    Route::post('/add', ['uses'=>'PermissionController@create','as'=>'add'])->middleware('can:permission-add');
    Route::post('/delete', ['uses'=>'PermissionController@delete','as'=>'delete'])->middleware('can:permission-add');
});

Route::group(['prefix' =>ROOT_DIR.'setting', 'middleware' => 'auth', 'as' => 'setting.'], function () {
    Route::get('/list', ['uses'=>'SettingController@index', 'as'=>'index'])->middleware('can:setting-list');
    Route::post('/store_max_image_size', ['uses'=>'SettingController@store_max_image_size', 'as'=>'store_max_image_size'])->middleware('can:setting-change');
    Route::post('/store_max_file_size', ['uses'=>'SettingController@store_max_file_size', 'as'=>'store_max_file_size'])->middleware('can:setting-change');
    Route::post('/logo', ['uses'=>'SettingController@store_logo', 'as'=>'store_logo'])->middleware('can:setting-change');
    Route::post('/contact_info', ['uses'=>'SettingController@store_contact_info', 'as'=>'contact_info'])->middleware('can:setting-change');
});

Route::group(['prefix' =>ROOT_DIR.'profile', 'middleware' => 'auth', 'as' => 'profile.'], function () {
    Route::get('/view/{id}', ['uses'=>'ProfileController@view','as'=>'view']);
    Route::post('/update/{type}', ['uses'=>'ProfileController@update','as'=>'update']);
});

Route::group(['prefix' =>ROOT_DIR.'slider', 'middleware' => 'auth', 'as' => 'slider.'], function () {
    Route::get('/list', ['uses'=>'SliderController@index','as'=>'index'])->middleware('can:slider-list');
    Route::post('/add', ['uses'=>'SliderController@create','as'=>'add'])->middleware('can:slider-add');
    Route::get('/edit/{slider_id}', ['uses'=>'SliderController@edit','as'=>'edit'])->middleware('can:slider-add');
    Route::post('/update', ['uses'=>'SliderController@update','as'=>'update'])->middleware('can:slider-add');
    Route::get('/activate/{id}/{action}', ['uses'=>'SliderController@set_active','as'=>'activate'])->middleware('can:slider-add');
    Route::post('/delete', ['uses'=>'SliderController@delete','as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'pages', 'middleware' => 'auth', 'as' => 'pages.'], function () {
    Route::get('/list', ['uses'=>'PostController@index','as'=>'index'])->middleware('can:pages-list');
    Route::get('/add', ['uses'=>'PostController@create','as'=>'add'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'PostController@store'])->middleware('can:pages-add');
    Route::get('/edit/{id}', ['uses'=>'PostController@edit', 'as'=> 'edit'])->middleware('can:pages-edit');
    Route::post('/update', ['uses'=>'PostController@update', 'as'=> 'update'])->middleware('can:pages-edit');
    Route::post('/create_url', ['uses'=>'PostController@create_url', 'as'=>'create_url'])->middleware('can:pages-add');
    Route::post('/recycle', ['uses'=>'PostController@recycle', 'as'=>'recycle'])->middleware('can:pages-delete');
    Route::post('/make_featured', ['uses'=>'PostController@make_featured', 'as'=>'make_featured']);
});

Route::group(['prefix' =>ROOT_DIR.'menu', 'middleware' => 'auth', 'as' => 'menu.'], function () {
    Route::get('/list', ['uses'=>'MenuController@index','as'=>'index'])->middleware('can:menu-list');
    Route::post('/add', ['uses'=>'MenuController@create','as'=>'add'])->middleware('can:menu-add');
    Route::post('/change', ['uses'=>'MenuController@change','as'=>'change'])->middleware('can:menu-add');
    Route::get('/remove_item/{menu_post_id}', ['uses'=>'MenuController@remove_item','as'=>'remove_item'])->middleware('can:menu-add');
    Route::post('/edit_menu', ['uses'=>'MenuController@edit_menu','as'=>'edit_menu'])->middleware('can:menu-add');
    Route::post('/saveOrder', ['uses'=>'MenuController@saveOrder','as'=>'saveOrder'])->middleware('can:menu-add');
    Route::get('/change_status/{menu_id}/{action}', ['uses'=>'MenuController@change_status','as'=>'change_status'])->middleware('can:menu-add');
});

Route::group(['prefix' =>ROOT_DIR.'gallery', 'middleware' => 'auth', 'as' => 'gallery.'], function () {
    Route::get('/list', ['uses'=>'GalleryController@index','as'=>'index'])->middleware('can:gallery-list');
    Route::post('/add', ['uses'=>'GalleryController@create','as'=>'add'])->middleware('can:gallery-add');
    Route::get('/view/{id}', ['uses'=>'GalleryController@display','as'=>'view'])->middleware('can:gallery-list');
    Route::post('/edit', ['uses'=>'GalleryController@edit','as'=>'edit'])->middleware('can:gallery-edit');
    Route::post('/delete_gallery', ['uses'=>'GalleryController@delete_gallery','as'=>'delete_gallery'])->middleware('can:gallery-delete');
    Route::group(['prefix' =>'image', 'middleware' => 'auth', 'as' => 'image.'], function () {
        Route::post('/add', ['uses'=>'GalleryController@add_image','as'=>'add'])->middleware('can:gallery-edit');
        Route::post('/delete', ['uses'=>'GalleryController@delete_image','as'=>'delete'])->middleware('can:gallery-delete');
    });
});

Route::group(['prefix' =>ROOT_DIR.'category', 'middleware' => 'auth', 'as' => 'category.'], function () {
    Route::get('/list', ['uses'=>'CategoryController@index','as'=>'index'])->middleware('can:category-list');
    Route::get('/list_item/{id}', ['uses'=>'CategoryController@list_item','as'=>'list_item'])->middleware('can:category-list');
    Route::post('/store', ['uses'=>'CategoryController@store', 'as'=>'store'])->middleware('can:category-add');
    Route::post('/delete', ['uses'=>'CategoryController@delete_category','as'=>'delete'])->middleware('can:category-list');
    Route::post('/update', ['uses'=>'CategoryController@update_category','as'=>'update'])->middleware('can:category-list');

    // Items
    Route::get('/add_item/{category_id}', ['uses'=>'CategoryController@add_item', 'as'=>'add_item'])->middleware('can:category-add');
    Route::post('/store_item', ['uses'=>'CategoryController@store_item', 'as'=>'store_item'])->middleware('can:category-add');
    Route::post('/update_item', ['uses'=>'CategoryController@update_item', 'as'=>'update_item'])->middleware('can:category-add');
    Route::get('/edit_item/{item_id}', ['uses'=>'CategoryController@edit_item', 'as'=>'edit_item'])->middleware('can:category-add');
    Route::post('/delete_item', ['uses'=>'CategoryController@delete_item', 'as'=>'delete_item'])->middleware('can:category-add');
});

Route::group(['prefix' =>ROOT_DIR.'downloads', 'middleware' => 'auth', 'as' => 'downloads.'], function () {
    Route::get('/list', ['uses'=>'DownloadController@index', 'as'=>'index'])->middleware('can:pages-add');
    Route::post('/add', ['uses'=>'DownloadController@store', 'as'=>'add'])->middleware('can:pages-add');
    Route::post('/edit', ['uses'=>'DownloadController@edit', 'as'=>'edit'])->middleware('can:pages-add');

resources/views/layouts/_partials/nav.blade.php
<nav class="navbar navbar-default navbar-static-top m-b-0">
	<div class="navbar-header">
		<!-- Toggle icon for mobile view -->
		<div class="top-left-part">
			<!-- Logo -->
			<a class="logo" href="{{ route('index') }}">
				<!-- Logo icon image, you can use font-icon also --><b>
					<!--This is dark logo icon-->
					<img src="{{ asset(STATIC_DIR.'assets/icons/logo_name.jpg') }}" alt="home" class="dark-logo" /><!--This is light logo icon-->
					<img src="{{ asset(STATIC_DIR.'assets/icons/logo_name.jpg') }}" alt="home" class="light-logo" />
				</b>
				<!-- Logo text image you can use text also --><span class="hidden-xs">
                        <!--This is dark logo text-->
					{{--<img src="{{ asset(STATIC_DIR.'plugins/images/admin-text.png') }}" alt="home" class="dark-logo" /><!--This is light logo text-->--}}
					{{--<img src="{{ asset(STATIC_DIR.'plugins/images/admin-text-dark.png') }}" alt="home" class="light-logo" />--}}
                     </span> </a>
		</div>
		<!-- /Logo -->
		<!-- Search input and Toggle icon -->
		<ul class="nav navbar-top-links navbar-left">
			<li><a href="javascript:void(0)" class="open-close waves-effect waves-light"><i class="ti-menu"></i></a></li>
			{{--<li class="dropdown">--}}
				{{--<a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i class="mdi mdi-gmail"></i>--}}
					{{--<div class="notify"><span class="heartbit"></span><span class="point"></span></div>--}}
				{{--</a>--}}
				{{--<ul class="dropdown-menu mailbox animated bounceInDown">--}}
					{{--<li>--}}
						{{--<div class="drop-title">You have 4 new messages</div>--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--<div class="message-center">--}}
							{{--<a href="#">--}}
								{{--<div class="user-img"> <img src="{{ asset(STATIC_DIR.'plugins/images/users/pawandeep.jpg') }}" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>--}}
								{{--<div class="mail-contnet">--}}
									{{--<h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>--}}
							{{--</a>--}}
						{{--</div>--}}
					{{--</li>--}}
					{{--<li>--}}
						{{--<a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i class="fa fa-angle-right"></i> </a>--}}
					{{--</li>--}}
				{{--</ul>--}}
				{{--<!-- /.dropdown-messages -->--}}
			{{--</li>--}}
			<!-- .Task dropdown -->
			{{--<li class="dropdown">--}}
				{{--<a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i class="mdi mdi-check-circle"></i>--}}
					{{--<div class="notify"><span class="heartbit"></span><span class="point"></span></div>--}}
				{{--</a>--}}
				{{--<ul class="dropdown-menu dropdown-tasks animated slideInUp">--}}
					{{--<li>--}}
						{{--<a href="javascript:void(0)">--}}
							{{--<div>--}}
								{{--<p> <strong>Task 1</strong> <span class="pull-right text-muted">40% Complete</span> </p>--}}
								{{--<div class="progress progress-striped active">--}}
									{{--<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"> <span class="sr-only">40% Complete (success)</span> </div>--}}
								{{--</div>--}}
							{{--</div>--}}
						{{--</a>--}}
					{{--</li>--}}
					{{--<li class="divider"></li>--}}
					{{--<li>--}}
						{{--<a class="text-center" href="#"> <strong>See All Tasks</strong> <i class="fa fa-angle-right"></i> </a>--}}
					{{--</li>--}}
				{{--</ul>--}}
			{{--</li>--}}
			<!-- .Megamenu -->
			{{--<li class="mega-dropdown"> <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><span class="hidden-xs">Mega</span> <i class="icon-options-vertical"></i></a>--}}
				{{--<ul class="dropdown-menu mega-dropdown-menu animated bounceInDown">--}}
					{{--<li class="col-sm-3">--}}
						{{--<ul>--}}
							{{--<li class="dropdown-header">Header Title</li>--}}
							{{--<li><a href="javascript:void(0)">Link of page</a> </li>--}}
						{{--</ul>--}}
					{{--</li>--}}
					{{--<li class="col-sm-3">--}}
						{{--<ul>--}}
							{{--<li class="dropdown-header">Header Title</li>--}}
							{{--<li><a href="javascript:void(0)">Link of page</a> </li>--}}
						{{--</ul>--}}
					{{--</li>--}}
					{{--<li class="col-sm-3">--}}
						{{--<ul>--}}
							{{--<li class="dropdown-header">Header Title</li>--}}
							{{--<li><a href="javascript:void(0)">Link of page</a> </li>--}}
						{{--</ul>--}}
					{{--</li>--}}
					{{--<li class="col-sm-3">--}}
						{{--<ul>--}}
							{{--<li class="dropdown-header">Header Title</li>--}}
							{{--<li> <a href="javascript:void(0)">Link of page</a> </li>--}}
						{{--</ul>--}}
					{{--</li>--}}
				{{--</ul>--}}
			{{--</li>--}}
			<!-- /.Megamenu -->
		</ul>
		<!-- This is the message dropdown -->
		<ul class="nav navbar-top-links navbar-right pull-right">
			<!-- /.Task dropdown -->
			<!-- /.dropdown -->
			{{--<li>--}}
				{{--<form role="search" class="app-search hidden-sm hidden-xs m-r-10">--}}
					{{--<input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a> </form>--}}
			{{--</li>--}}
			<li class="dropdown">
				<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
					<img src="{{ asset(STATIC_DIR.DEFAULT_USER) }}" alt="user-img" width="36" class="img-circle">
					<b class="hidden-xs">{{ Auth::user()->first_name }}</b><span class="caret"></span>
				</a>
				<ul class="dropdown-menu dropdown-user animated flipInY">
					<li>
						<div class="dw-user-box">
							<div class="u-img"><img src="{{ asset(STATIC_DIR.DEFAULT_USER) }}" alt="user" /></div>
							<div class="u-text">
                                <h4>{{ Auth::user()->first_name }} {{ Auth::user()->last_name }}</h4>
                                <p class="text-muted">{{ Auth::user()->email }}</p>
                                <a href="{{ route('profile.view',Auth::user()->id) }}" class="btn btn-rounded btn-danger btn-sm">View Profile</a></div>
						</div>
					</li>
					<li role="separator" class="divider"></li>
					<li><a href="{{ route('profile.view',Auth::user()->id) }}"><i class="ti-user"></i> My Profile</a></li>
					<li role="separator" class="divider"></li>
					<li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
					<li role="separator" class="divider"></li>
					<li class="pull-right" style="padding-right: 20px;">
						<form id="logout-form" action="{{ route('logout') }}" method="POST" >
							@csrf
							<button type="submit" class="btn btn-default btn-flat"><i class="fa fa-power-off"></i>&nbsp;Logout</button>
						</form>
					</li>
				</ul>
				<!-- /.dropdown-user -->
			</li>
			
			
			
			<!-- /.dropdown -->
		</ul>
	</div>
	<!-- /.navbar-header -->
	<!-- /.navbar-top-links -->
	<!-- /.navbar-static-side -->
</nav>

resources/views/layouts/_partials/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav slimscrollsidebar">
		<div class="sidebar-head">
			<h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3> </div>
		<ul class="nav" id="side-menu">
			<li class="user-pro">
				<a href="#" class="waves-effect"><img src="{{ asset(STATIC_DIR.DEFAULT_USER) }}" alt="user-img" class="img-circle">
					<span class="hide-menu"> {{ Auth::user()->first_name ?? ''  }} {{ Auth::user()->last_name ?? ''  }}</span>
				</a>

			</li>
			<li> <a href="{{ route('home') }}" class="waves-effect @if(Request::is('admin')) active @endif">
					<i class="mdi mdi-av-timer fa-fw"></i>
					<span class="hide-menu">Dashboard</span>
				</a>
			</li>
			<li> <a href="{{ route('permission.index') }}" class="@if(Request::is(ROOT_DIR.'permission/*')) active @endif">
					<i class="mdi mdi-lock fa-fw" data-icon="v"></i>
					<span class="hide-menu"> Permissions</span>
				</a>
			</li>
			<li> <a href="{{ route('setting.index') }}" class="@if(Request::is(ROOT_DIR.'setting/*')) active @endif">
					<i class="mdi mdi-settings fa-fw" data-icon="v"></i>
					<span class="hide-menu"> Settings</span>
				</a>
			</li>
			<li class="devider"></li>
			<li class="text-center" style="color: white; font-weight: bold;">MAIN NAVIGATION</li>
			<li class="devider"></li>
			@canany(['user-add','user-list'])
				<li>
					<a href="#" class="waves-effect @if(Request::is(ROOT_DIR.'user/*')) active @endif">
						<i class="mdi mdi-account-multiple fa-fw"></i>
						<span class="hide-menu">Users<span class="fa arrow open"></span></span>
					</a>
					<ul class="nav nav-second-level @if(Request::is(ROOT_DIR.'user/*')) collapse in @endif">
						<li>
							<a class="@if(Request::is(ROOT_DIR.'user/register')) active @endif" href="{{ route('user.register') }}">
								<i class="mdi mdi-account-multiple-plus fa-fw"></i> <span class="hide-menu">Add</span>
							</a>
						</li>
						<li>
							<a class="@if(Request::is(ROOT_DIR.'user/list')) active @endif" href="{{ route('user.index') }}">
								<i class="mdi mdi-format-list-bulleted fa-fw"></i> <span class="hide-menu">List</span>
							</a>
						</li>
					</ul>
				</li>
			@endcanany
			@can('slider-list')
				<li> <a href="{{ route('slider.index') }}" class="@if(Request::is(ROOT_DIR.'slider/*')) active @endif">
						<i class="mdi mdi-airplay fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Slider</span>
					</a>
				</li>
			@endcan
            @can('popup-list')
                <li> <a href="{{ route('popup.index') }}" class="@if(Request::is(ROOT_DIR.'popup/*')) active @endif">
                        <i class="mdi mdi-airplay fa-fw" data-icon="v"></i>
                        <span class="hide-menu"> Popup</span>
                    </a>
                </li>
            @endcan
			@can('post-list')
				<li>
					<a href="{{ route('weblink.index') }}" class="@if(Request::is(ROOT_DIR.'weblink/*')) active @endif">
						<i class="mdi mdi-link fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Web Links</span>
					</a>
				</li>
			@endcan
			@can('pages-list')
				<li>
					<a href="#" class="waves-effect @if(Request::is(ROOT_DIR.'pages/*')) active @endif">
						<i class="mdi mdi-image-filter-none fa-fw"></i>
						<span class="hide-menu">Pages<span class="fa arrow open"></span></span>
					</a>
					<ul class="nav nav-second-level @if(Request::is(ROOT_DIR.'pages/*')) collapse in @endif">
						<li>
							<a class="@if(Request::is(ROOT_DIR.'pages/add')) active @endif" href="{{ route('pages.add') }}">
								<i class="mdi mdi-plus fa-fw"></i> <span class="hide-menu">Create new page</span>
							</a>
						</li>
						<li>
							<a class="@if(Request::is(ROOT_DIR.'pages/list')) active @endif" href="{{ route('pages.index') }}">
								<i class="mdi mdi-format-list-bulleted fa-fw"></i> <span class="hide-menu">All pages</span>
							</a>
						</li>
					</ul>
			@endcan
			@can('menu-list')
				<li> <a href="{{ route('menu.index') }}" class="@if(Request::is(ROOT_DIR.'menu/*')) active @endif">
						<i class="mdi mdi-apps fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Menu</span>
					</a>
				</li>
			@endcan
			@can('menu-list')
				<li>
					<a data-src="{{ URL(STATIC_DIR.'laravel-filemanager?type=Images') }}" href="javascript:;" data-fancybox data-type="iframe" class="@if(Request::is(ROOT_DIR.'media/*')) active @endif">
						<i class="mdi mdi-camera-iris fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Media</span>
					</a>
				</li>
			@endcan
			@can('menu-list')
				<li> <a href="{{ route('gallery.index') }}" class="@if(Request::is(ROOT_DIR.'gallery/*')) active @endif">
						<i class="mdi mdi-folder-multiple-image fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Gallery</span>
					</a>
				</li>
			@endcan
			@can('menu-list')
				<li> <a href="{{ route('category.index') }}" class="@if(Request::is(ROOT_DIR.'category/*')) active @endif">
						<i class="mdi mdi-group fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Category</span>
					</a>
				</li>
			@endcan
			@can('menu-list')
				<li> <a href="{{ route('downloads.index') }}" class="@if(Request::is(ROOT_DIR.'downloads/*')) active @endif">
						<i class="mdi mdi-download fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Downloads</span>
					</a>
				</li>
			@endcan
			@can('jobs-list')
				<li>
					<a href="#" class="waves-effect @if(Request::is(ROOT_DIR.'jobs/*')) active @endif">
						<i class="mdi mdi-briefcase fa-fw"></i>
						<span class="hide-menu">Job Portal<span class="fa arrow open"></span></span>
					</a>
					<ul class="nav nav-second-level @if(Request::is(ROOT_DIR.'jobs/*')) collapse in @endif">
						<li>
							<a class="@if(Request::is(ROOT_DIR.'jobs/add')) active @endif" href="{{ route('jobs.add') }}">
								<i class="mdi mdi-plus fa-fw"></i> <span class="hide-menu">Create new job</span>
							</a>
						</li>
						<li>
							<a class="@if(Request::is(ROOT_DIR.'jobs/list')) active @endif" href="{{ route('jobs.index') }}">
								<i class="mdi mdi-format-list-bulleted fa-fw"></i> <span class="hide-menu">All jobs</span>
							</a>
						</li>
						<li>
							<a class="@if(Request::is(ROOT_DIR.'jobs/user/*')) active @endif" href="{{ route('jobs.user.index') }}">
								<i class="mdi mdi-account-multiple fa-fw"></i> <span class="hide-menu">Registered Users</span>
							</a>
						</li>
					</ul>
				</li>
			@endcan
            @can('form-list')
                <li> <a href="{{ route('form.index') }}" class="@if(Request::is(ROOT_DIR.'form/*')) active @endif">
                        <i class="mdi mdi-file fa-fw" data-icon="v"></i>
                        <span class="hide-menu"> Request Form</span>
                    </a>
                </li>
            @endcan
			<li style="padding-bottom: 100px;"></li>
		</ul>
	</div>
</div>